### ISSUE TITLE
Cannot find lib 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend'

### ISSUE THREAD

**Issue by AlexFundorin** [Gerstmann-Bradley/Mograph-Presets-of-Geometry-Nodes#2]
How do I remove any mention of your addon from my startup file?
Tried to uninstall the addon, delete every trace and resave the startup file. Yet, it's still there, in the log.
Mind you, that I'm already using Blender 3.5 and the log is referring to 3.3. It also searches for some data in "C:\Users\blender\git" folder, which have never existed.
https://i.imgur.com/iUITEJP.png

`Read prefs: C:\Blender\3.5\config\userpref.blend
Info: Read library:  'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend', 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend', parent '<direct>'
Info: Read library:  'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend', 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend', parent '<direct>'
Warning: Unable to open 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend': No such file or directory
Info: Cannot find lib 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend'
Info: Cannot find lib 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend'
Info: LIB: NodeTree: 'G_Pi Factor' missing from 'C:\Blender\3.3\scripts\addons\Bradley's Geo Node Presets\Data\3.1\preset.blend', parent '<direct>'
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetString' is deprecated and will be removed in Blender 3.7.`

**Comment by Gerstmann-Bradley** [comment]
more likely bugs and some trash message due to dirty codes, but unfortunately the addon is no longer maintained by its original author and the source code isnt released.

If you have removed the addon and the issue isnt solved, I think the easiest solution is to re-install whole blender.

**Comment by Gerstmann-Bradley** [comment]
Now I rethink about it. 
 I assume you are opening your old file with the preset, and the previous link was established in 3.3.
So even if you are opening it with 3.5, it's trying to look for 3.3 folder.
if you goes to the outliner and check the linking status. You should find your old linked library.
You can right click and choose to relocate it or delete it. It's up to you.
![image](https://github.com/Gerstmann-Bradley/Mograph-Presets-of-Geometry-Nodes/assets/55994236/3a7de548-4c21-4614-8372-57c30a50ce72)

Since this ticket has no response for more then a year, and you seem no longer using it. I will close this ticket.
